### ISSUE TITLE
Swift: Error messages do not use description of object

### ISSUE THREAD

**Issue by NebulaFox** [Quick/Nimble#91] opened 2015-02-11 17:00 UTC
I have some enums and structs that, by an extensions, support printable, but the results always come out as defined in their description methods. The types are generally used in an array.

Xcode 6.1.1

**Comment by jeffh** [comment] 2015-02-12 09:05
Hey @NebulaFox, could you elaborate more on this or give me an example? I'm not quite sure what you mean. I tried this example, but I got what seems to me as reasonable results:

```swift
struct Foo {}
extension Foo: Printable {
    var description: String { return "LOL" }
}

var f: [Foo]? = [Foo()]
expect(f).to(beNil()) // message: "failed - expected to be nil, got <[LOL]>"
```

**Comment by NebulaFox** [comment] 2015-02-12 12:36
import Foundation
    import Nimble
    import Quick

    enum SpamEggs : Printable {
        case Spam
        case Eggs
        
        var description: String {
            switch self {
                case .Spam:
                    return "SpamEggs.Spam"
                case .Eggs:
                    return "SpamEggs.Eggs"
            }
        }
    }


    struct Foo : Printable {
        let spamEggs:SpamEggs

        init(spamEggs:SpamEggs) {
            self.spamEggs = spamEggs
        }
        
        var description:String {
            return "Foo{\(spamEggs)}"
        }
    }

    class PrintSpec: QuickSpec {
        override func spec() {
            it("should fail") {
                let foo:Foo? = Foo(spamEggs: SpamEggs.Eggs)
                expect(foo).to(beNil())
            }
        }
    }

gives me

    Test Suite 'All tests' started at 2015-02-12 11:47:25 +0000
    Test Suite 'Quick.framework' started at 2015-02-12 11:47:25 +0000
    Test Suite 'Quick.framework' passed at 2015-02-12 11:47:25 +0000.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
    Test Suite 'UnexpectedPrintTests.xctest' started at 2015-02-12 11:47:25 +0000
    Test Suite 'PrintSpec' started at 2015-02-12 11:47:25 +0000
    Test Case '-[UnexpectedPrintTests.PrintSpec should_fail]' started.
    /Users/robbiebykowski/Desktop/UnexpectedPrint/UnexpectedPrintTests/PrintSpec.swift:44: error: -[UnexpectedPrintTests.PrintSpec should_fail] : failed - expected to be nil, got <UnexpectedPrintTests.Foo>
    Test Case '-[UnexpectedPrintTests.PrintSpec should_fail]' failed (0.009 seconds).
    Test Suite 'PrintSpec' failed at 2015-02-12 11:47:25 +0000.
	     Executed 1 test, with 1 failure (0 unexpected) in 0.009 (0.010) seconds
    Test Suite 'UnexpectedPrintTests.xctest' failed at 2015-02-12 11:47:25 +0000.
	     Executed 1 test, with 1 failure (0 unexpected) in 0.009 (0.010) seconds
    Test Suite 'All tests' failed at 2015-02-12 11:47:25 +0000.
	     Executed 1 test, with 1 failure (0 unexpected) in 0.009 (0.015) seconds

so it appears it doesn't work for me

    failed - expected to be nil, got <UnexpectedPrintTests.Foo>

**Comment by jeffh** [comment] 2015-02-14 01:44
Thanks for the example.

Hm, I still get the sample behavior has before:

```swift

enum SpamEggs : Printable {
    case Spam
    case Eggs

    var description: String {
        switch self {
            case .Spam:
                return "SpamEggs.Spam"
            case .Eggs:
                return "SpamEggs.Eggs"
        }
    }
}


struct Foo : Printable {
    let spamEggs:SpamEggs

    init(spamEggs:SpamEggs) {
        self.spamEggs = spamEggs
    }

    var description:String {
        return "Foo{\(spamEggs)}"
    }
}

class FooTest: XCTestCase {
    func testStringification() {
        let foo:Foo? = Foo(spamEggs: SpamEggs.Eggs)
        expect(foo).to(beNil()) // "failed - expected to be nil, got <Foo{SpamEggs.Eggs}>"

        let foo2:[Foo]? = [Foo(spamEggs: SpamEggs.Eggs)]
        expect(foo2).to(beNil())  // "failed - expected to be nil, got <[Foo{SpamEggs.Eggs}]>"
    }
}
```

Xcode 6.1.1 and Xcode 6.3 beta have the same behavior for me.

I wonder if this a Quick + Nimble integration issue. Further investigation is required, I'll take a look at it when I get some free time, thanks @NebulaFox.

**Comment by jeffh** [comment] 2015-02-17 21:35
I tried this with Quick, and I still have the same problem. Do you have a sample project that shows this behavior you're describing?

![screen shot 2015-02-17 at 1 31 27 pm](https://cloud.githubusercontent.com/assets/68616/6237680/bb16ff38-b6a9-11e4-8bd7-5f51403ea489.png)

I tried this on Xcode 6.1 and 6.3 beta. I still have the same string output as I shown previously.

**Comment by NebulaFox** [comment] 2015-02-20 14:58
I have uploaded my project, https://github.com/NebulaFox/Unexpected-Print
and here is screen shot of my errors

![screen shot 2015-02-20 at 14 45 47](https://cloud.githubusercontent.com/assets/1708386/6288418/c904e97a-b910-11e4-9fb0-c81fb30de60e.png)

**Comment by jeffh** [comment] 2015-05-05 06:27
(╯°□°）╯︵ ┻━┻

I only managed to ever get it to reproduce once on Xcode 6.1. But not since then :(.

I'll probably close this issue in a few days since I haven't gotten it to reproduce on Xcode 6.3. But let me know otherwise if you have the time. Sorry, :sob:.

**Closed** 2015-05-16 20:24 UTC
Labels: bug, help wanted
