### ISSUE TITLE
Compiler Error for tvOS target

### ISSUE THREAD

**Issue by kkiermasz** [Quick/Nimble#833] opened 2020-09-22 15:38 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Tried to build a test target for tvOS using `Nimble`.

### What actually happened instead?

Compiler Error:

`Cannot find type 'BadInstructionException' in scope` in `ThrowAssertion.swift` at line 13.

### Environment

List the software versions you're using:

- Nimble: *8.1.2*
- Xcode Version: *12.0 (12A7209)*
- Swift Version: *5.3*
- Swift Package Manager *Swift Package Manager - Swift 5.3.0*

**Comment by ikesyo** [comment] 2020-09-25 15:03
Duplicate of #816. Could you please try Nimble v9 which is currently in RC state: https://github.com/Quick/Nimble/releases/tag/v9.0.0-rc.3.

**Closed by ikesyo** 2020-09-25 15:03 UTC

**Comment by kkiermasz** [comment] 2020-09-26 07:12
It works. Thanks a million!

**Comment by CaioSym** [comment] 2021-06-03 15:18
I'm still hitting this on 9.2.0!. 
9.1.0 works fine but as soon as I bump its back.
