### ISSUE TITLE
Bitrise build throwing error "library not found for -lswiftXCTest"

### ISSUE THREAD

**Issue by Tavernari** [Quick/Nimble#865] opened 2021-04-13 01:51 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I am trying to build my project on Bitrise with XCode 12

### What did you expect to happen?

I expected the build works

### What actually happened instead?

It crash when the build was linking Nimble

### Environment

List the software versions you're using:

- Quick: 3.1.2
- Nimble: 9.0.0
- Xcode Version: 12.5 
- Swift Version: 5

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Cocoapods: 1.10.1

## Error log

...
▸ Generating 'Stories.framework.dSYM'
▸ Linking RxCocoa
▸ Compiling mach_excServer.c
▸ Linking RxCocoa
▸ Compiling XCTestObservationCenter+Register.m
▸ Generating 'Quick.framework.dSYM'
▸ Compiling Nimble_vers.c
▸ Generating 'RxCocoa.framework.dSYM'
▸ Compiling Nimble-dummy.m
▸ Compiling NMBStringify.m
▸ Compiling NMBExceptionCapture.m
▸ Compiling DSL.m
▸ Compiling CwlMachBadInstructionHandler.m
▸ Compiling CwlCatchException.m
▸ Compiling mach_excServer.c
▸ Compiling XCTestObservationCenter+Register.m
▸ Linking Nimble
❌  ld: library not found for -lswiftXCTest
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
...

**Comment by ikesyo** [comment] 2021-04-13 01:59
Duplicate of #855. I'll release a new version including the fix shortly.

**Closed by ikesyo** 2021-04-13 01:59 UTC
