### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by bcardarella** [Quick/Nimble#870] opened 2021-04-30 15:02 UTC
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I am attempting to build a project using Nimble with Carthage

### What did you expect to happen?

I would expect it to build

### What actually happened instead?

The build failed on Nimble-tvOS

### Environment

List the software versions you're using:

- Quick: *v.3.1.1*
- Nimble: *v9.0.0*
- Xcode Version: *v12.5 (12E262)*
- Swift Version: *v5.4*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Carthage: *v0.37.0*

### Project that demonstrates the issue

Gist of my build output: https://gist.github.com/bcardarella/cc85ee4a3287e6008963ba4cb0d3a39e

**Comment by VidaHasan** [comment] 2021-04-30 19:11
I am getting a similar issue

**Comment by bcardarella** [comment] 2021-04-30 19:45
@VidaHasan I bumped to v9.0.1 and it appears to be resolved

**Comment by VidaHasan** [comment] 2021-04-30 20:15
awesome, thanks for letting me know. I will try that and report back. :)

**Comment by ikesyo** [comment] 2021-04-30 22:26
Duplicate of #855 and #865.

**Closed by ikesyo** 2021-04-30 22:26 UTC
