### ISSUE TITLE
Compile error when using expect function with closure

### ISSUE THREAD

**Issue by kkiermasz** [Quick/Nimble#826] opened 2020-09-17 12:50 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I have updated Xcode to the newest version (which is provided with the newest Swift 5.3 as well) and Xcode failed to build test scheme. I have found out which lines caused that, but I think this is not my fault :P

### What did you expect to happen?

I have a simple wrapper function for an `Optional` which returns me unwrapped value or throws an error provided as an argument, when none is set.

I have a bunch of simple unit tests. Some of them check if valued is returned properly and others check if functions is throwing given error. All of these prevent the project from being built.

### What actually happened instead?

Here is an example using Nimble (which causes an error):

```
let emptyValue: Int? = nil
expect { try emptyValue.value(orThrow: ErrorMock()) }.to(throwError())
```

But when I use pure XCTest as below, instead of Nimble, test scheme is being built and tests run fine.

```
XCTAssertThrowsError(try emptyValue.value(orThrow: ErrorMock()))
```

Here is the compiler message for `Error: Illegal instruction: 4`:

```
1.	Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
2.	While evaluating request TypeCheckSourceFileRequest(source_file "<TestsDirectoryRootPath>/Tests/ExtensionsTests/Optionals/Optional+Extensions+Tests.swift")
3.	While evaluating request TypeCheckFunctionBodyUntilRequest(ExtensionsTests.(file).Optional_Extensions_Tests.test_ValueOrThrow()@<TestsDirectoryRootPath>/Tests/ExtensionsTests/Optionals/Optional+Extensions+Tests.swift:25:10, )
4.	While type-checking statement at [<TestsDirectoryRootPath>/Tests/ExtensionsTests/Optionals/Optional+Extensions+Tests.swift:25:30 - line:32:5] RangeText="{
        let emptyValue: Int? = nil
        expect { try emptyValue.value(orThrow: ErrorMock()) }.to(throwError())
        
        let notEmptyValue: Int? = 1
        XCTAssertNoThrow(try notEmptyValue.value(orThrow: ErrorMock()))
        XCTAssertEqual(try notEmptyValue.value(orThrow: ErrorMock()), 1)
    "
5.	While type-checking expression at [<TestsDirectoryRootPath>/Tests/ExtensionsTests/Optionals/Optional+Extensions+Tests.swift:27:9 - line:27:78] RangeText="expect { try emptyValue.value(orThrow: ErrorMock()) }.to(throwError()"
0  swift                    0x0000000105164865 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  swift                    0x0000000105163865 llvm::sys::RunSignalHandlers() + 85
2  swift                    0x0000000105164e1f SignalHandler(int) + 111
3  libsystem_platform.dylib 0x00007fff724e55fd _sigtramp + 29
4  libsystem_kernel.dylib   0x00007fff7243135e __ioctl + 10
5  swift                    0x00000001019b0073 (anonymous namespace)::ExprRewriter::coerceCallArguments(swift::Expr*, swift::AnyFunctionType*, swift::ConcreteDeclRef, swift::ApplyExpr*, llvm::ArrayRef<swift::Identifier>, swift::constraints::ConstraintLocatorBuilder) + 8899
6  swift                    0x00000001019acfb2 (anonymous namespace)::ExprRewriter::finishApply(swift::ApplyExpr*, swift::Type, swift::constraints::ConstraintLocatorBuilder, swift::constraints::ConstraintLocatorBuilder) + 11970
7  swift                    0x00000001019b87bd (anonymous namespace)::ExprRewriter::visitApplyExpr(swift::ApplyExpr*) + 477
8  swift                    0x000000010198f752 (anonymous namespace)::ExprWalker::walkToExprPost(swift::Expr*) + 18
9  swift                    0x0000000101985e33 (anonymous namespace)::ExprWalker::rewriteTarget(swift::constraints::SolutionApplicationTarget) + 371
10 swift                    0x0000000101985b20 swift::constraints::ConstraintSystem::applySolution(swift::constraints::Solution&, swift::constraints::SolutionApplicationTarget) + 6400
11 swift                    0x0000000101b6ebaa swift::TypeChecker::typeCheckExpression(swift::constraints::SolutionApplicationTarget&, bool&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 1242
12 swift                    0x0000000101b6e618 swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::TypeLoc, swift::ContextualTypePurpose, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 360
13 swift                    0x0000000101c53c3b swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 9115
14 swift                    0x0000000101c4f47a bool (anonymous namespace)::StmtChecker::typeCheckStmt<swift::BraceStmt>(swift::BraceStmt*&) + 314
15 swift                    0x0000000101c4de87 swift::TypeCheckFunctionBodyUntilRequest::evaluate(swift::Evaluator&, swift::AbstractFunctionDecl*, swift::SourceLoc) const + 2231
16 swift                    0x0000000101c56c6d llvm::Expected<swift::TypeCheckFunctionBodyUntilRequest::OutputType> swift::Evaluator::getResultCached<swift::TypeCheckFunctionBodyUntilRequest, (void*)0>(swift::TypeCheckFunctionBodyUntilRequest const&) + 925
17 swift                    0x0000000101c4ef28 swift::TypeCheckFunctionBodyUntilRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckFunctionBodyUntilRequest>(swift::Evaluator&, swift::TypeCheckFunctionBodyUntilRequest, swift::TypeCheckFunctionBodyUntilRequest::OutputType) + 440
18 swift                    0x0000000101c8c894 swift::TypeCheckSourceFileRequest::evaluate(swift::Evaluator&, swift::SourceFile*) const + 1380
19 swift                    0x0000000101c8f4a9 llvm::Expected<swift::TypeCheckSourceFileRequest::OutputType> swift::Evaluator::getResultUncached<swift::TypeCheckSourceFileRequest>(swift::TypeCheckSourceFileRequest const&) + 953
20 swift                    0x0000000101c8c1a4 swift::TypeCheckSourceFileRequest::OutputType swift::evaluateOrDefault<swift::TypeCheckSourceFileRequest>(swift::Evaluator&, swift::TypeCheckSourceFileRequest, swift::TypeCheckSourceFileRequest::OutputType) + 164
21 swift                    0x0000000100e0755b swift::CompilerInstance::performSemaUpTo(swift::SourceFile::ASTStage_t) + 6859
22 swift                    0x0000000100cc82fd swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 6845
23 swift                    0x0000000100c4cc07 main + 1255
24 libdyld.dylib            0x00007fff722eccc9 start + 1
```

### Environment

List the software versions you're using:

- Nimble: *8.1.2*
- Xcode Version: *12.0 (12A7209)*
- Swift Version: *5.3*

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager *Swift Package Manager - Swift 5.3.0*

### Project that demonstrates the issue

https://github.com/kkiermasz/NimbleExpectErrorExample

Simply open project in Xcode and run the tests (<kbd>command</kbd> + <kbd>U</kbd>)

**Comment by ikesyo** [comment] 2020-09-17 12:51
Duplicate of #809.

**Closed by ikesyo** 2020-09-17 12:51 UTC
