### ISSUE TITLE
When integrating nimbe using swiftpm in a test case project, it failed.

### ISSUE THREAD

**Issue by iT-Boyer** [Quick/Nimble#950] opened 2021-12-06 05:43 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Please replace this with what you did.

### What did you expect to happen?

Please replace this with what you expected to happen.

### What actually happened instead?

Please replace this with what happened instead.

``` swift
#if SWIFT_PACKAGE
    XCTFail("\(message)", file: location.file, line: location.line)
#else
```

this error:

``` sh
Cannot find 'XCTFail' in scope
```

### Environment

List the software versions you're using:

- Quick: *4.0.0*
- Nimble: *9.2.1*
- Xcode Version: *13.1 (13A1030d)* (Open Xcode; In menubar: Xcode > About Xcode)
- Swift Version: *5.5.1* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager *swiftpm-5.5.0* (Use `swift build --version` in Terminal)

### Project that demonstrates the issue

Please link to a project we can download that reproduces the issue. Feel free
to delete this section if it's not relevant to the issue (eg - feature request).

https://github.com/Quick/QuickOnLinuxExample

The project should be [short, self-contained, and correct example](http://sscce.org/).

**Comment by younata** [comment] 2022-04-15 02:47
In the testing I just did, the QuickOnLinuxExample correctly builds and runs, with the single expected test failure. Moreover, I've been able to run Quick & Nimble on linux for years in my own projects.

Perhaps you accidentally included Nimble as a dependency in your app or library target, and not the test target?

I'm going to close this as I'm unable to reproduce it.

**Closed by younata** 2022-04-15 02:47 UTC
