### ISSUE TITLE
Ambiguous reference to member 'contain'

### ISSUE THREAD

**Issue by ecbrodie** [Quick/Nimble#403] opened 2017-03-04 00:08 UTC
- [x ] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Wrote a basic test using Quick and Nimble.
I wanted to use the `contain` matcher to assert on the contents of an array. Here my very simple test:

```swift
import Quick
import Nimble

class MySillyTest: QuickSpec {
  
  override func spec() {
    describe("example tests") {
      it("verifies array contents") {
        let myArray = ["a", "b", "c"]
        expect(myArray.count).to(equal(3))
        expect(myArray.count).to(contain("a"))
      }
    }
  }
}
```

### What did you expect to happen?

Test works.

### What actually happened instead?

I am getting a compile error in Xcode due to the following message:

> Ambiguous reference to member 'contain'

But this is crazy. I can cmd-click on `contain` and it will indeed find that method in the Nimble source code. 

I've also tried other things like explicitly referencing `Nimble.contain`, using an array value to the contain method instead of varargs strings and explicitly stating the type of `myArray` to `[String]`. Always the same error.

### Environment

List the software versions you're using:

 - Quick: *1.1.0*
 - Nimble: *6.0.1*
 - Xcode Version: *8.2 (8C38)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: Not sure...no option in Xcode for `Components -> Toolchains`
 - Cocoapods: *1.2.0*

### Project that demonstrates the issue

The source code should show the issue I'm facing. I unfortunately ran out of time while authoring this issue to create a Github project, so I can spend time tomorrow to create one.

**Comment by jeffh** [comment] 2017-03-07 07:04
Hey @ecbrodie,

It's not a great error message that Xcode gives, but essentially `contain` doesn't work with integers. I think you're looking for something like:

```swift
expect(myArray).to(contain("a"))
```

Instead of the length of `myArray`

There's a proposal to [add protocol extensions](https://github.com/Quick/Nimble/issues/217), but we're partially at the mercy of how Xcode decided to expose these type errors.

I'm closing the issue, but feel free to reopen if you think there's a different problem.

**Closed by jeffh** 2017-03-07 07:04 UTC

**Comment by ecbrodie** [comment] 2017-03-07 13:51
@jeffh Eek, I must have drank a bad batch of coffee before I submitted this issue. I should not have been applying the `contain` matcher onto the result of `myArray.count`, that semantically makes no sense. The correct line should have indeed been `expect(myArray).to(contain("a"))`.

I just tried the correct code in my Xcode IDE and I am happy to say that it compiled correctly and passed. **HOWEVER**, I am still running into this issue with the error message *Ambiguous reference to member 'contain'* when I am asserting on an array of objects instead of simple types like String or int. For example, the following code will produce the same error (regardless of `Foo` being a `struct` or a `class`):

```
  class Foo {
    let name: String
    
    public init(_ name: String) {
      self.name = name
    }
  }
  
  override func spec() {
    describe("example tests") {
      it("verifies array contents") {
        let foo1 = Foo("abc")
        let foo2 = Foo("def")
        let fooArray = [foo1, foo2]
        expect(fooArray).to(contain(foo1))
      }
    }
```

**Comment by jeffh** [comment] 2017-03-08 07:00
Hey Evan,

It’s probably because the `Foo` class isn’t Equatable. Try making it equatable and I’m guessing it’ll probably work.

- Jeff

**Comment by caynan** [comment] 2017-04-28 17:04
I'm having the same problem with a struct that implements the `equatable` protocol. And seeing the same error.

**Comment by jeffh** [comment] 2017-05-02 03:22
Hey @caynan,

Do you have a code sample that reproduces the issue you're having?

Thanks.

**Comment by serges147** [comment] 2019-03-05 09:49
Same problem. Sample is simple:
```
let someSet: Set<String> = ["a", "b", "c"]
expect(someSet).to(contain(["b", "c"]))
```

**Comment by serges147** [comment] 2019-03-05 09:53
It looks like any type which implements both `Sequence` and `SetAlgebra` is problematic for Nimble 8.

**Comment by serges147** [comment] 2019-03-05 09:54
BTW, the same problem for the `isEmpty()` matcher.

**Comment by serges147** [comment] 2019-03-05 11:40
I just noticed that this issue is 2 years old. Guys, please either reopen this issue or let me know if I have to create a new one (for Nimble 8).

**Comment by ikesyo** [comment] 2019-03-05 15:04
@serges147 What you wrote is not related this issue, but rather a duplicate of https://github.com/Quick/Nimble/issues/496#issuecomment-469632683.
