### ISSUE TITLE
Can't build when targeting tvOS.

### ISSUE THREAD

**Issue by danielsaidi** [Quick/Nimble#816] opened 2020-09-04 13:15 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I use Quick and Nimble and try to build my library for tvOS.

### What did you expect to happen?

The library should build.

### What actually happened instead?

Nimble doesn't build

### Environment

List the software versions you're using:

- Quick: 3.0.0
- Nimble: 8.0.0
- Xcode Version: 11.7
- Swift Version: 5.2

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Swift Package Manager 5.2

### Error

The build error occurs in `ThrowAssertion.swift` where a `tvOS` check occurs after a reference to `BadInstruction`, which doesn't support `tvOS`.

<img width="989" alt="image" src="https://user-images.githubusercontent.com/429927/92243028-0d739980-eec1-11ea-82e1-c1e3f1223bae.png">

<img width="541" alt="image" src="https://user-images.githubusercontent.com/429927/92243130-3f84fb80-eec1-11ea-90c6-7556728508d0.png">

**Comment by ikesyo** [comment] 2020-09-09 12:51
`throwAssertion` matcher is supported on tvOS as well. https://github.com/Quick/Nimble/blob/a24d6c8571db5328ee71980c2c7ac3c8a839f012/Carthage/Checkouts/CwlPreconditionTesting/Sources/CwlPosixPreconditionTesting/CwlCatchBadInstructionPosix.swift#L63 is used for tvOS and https://github.com/Quick/Nimble/blob/a24d6c8571db5328ee71980c2c7ac3c8a839f012/Carthage/Checkouts/CwlPreconditionTesting/Sources/CwlPreconditionTesting/CwlBadInstructionException.swift#L35 is used for iOS/macOS. Could you please provide how to reproduce or an example project?

**Comment by danielsaidi** [comment] 2020-09-09 13:00
I just try to build a project that imports `Quick` and `Nimble` for tvOS.

**Comment by ikesyo** [comment] 2020-09-09 13:14
> Nimble: 8.0.0
> Swift Package Manager 5.2

Okay I understand that this is a duplicate of #674. Please use Nimble v9 which is currently in RC state: https://github.com/Quick/Nimble/releases/tag/v9.0.0-rc.2.

**Closed** 2020-09-09 13:23 UTC
