### ISSUE TITLE
`Dependencies` directory does not get checked in Git when using CocoaPods and a standard `.gitignore` file

### ISSUE THREAD

**Issue by dirtyhenry** [Quick/Nimble#723] opened 2020-01-30 14:34 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Installed Nimble on a project where I followed CocoaPods recommendation and **did add `Pods` to my Git repo**. 

### What did you expect to happen?

My CI environment would be able to run my tests.

### What actually happened instead?

Since I'm using [this community-driven `.gitignore` for Swift](https://github.com/github/gitignore/blob/master/Swift.gitignore), I stumbled upon this error: 

```
❌  error: /Users/macosci/builds/oYyfaEoC/0/user/myapp/Pods/Nimble/Carthage/Checkouts/CwlPreconditionTesting/Dependencies/CwlCatchException/Sources/CwlCatchExceptionSupport/include/CwlCatchException.h: No such file or directory (in target 'Nimble' from project 'Pods')
```

Due to [this line](https://github.com/github/gitignore/blob/master/Swift.gitignore#L70) that prevented [this file](https://github.com/Quick/Nimble/blob/v8.0.5/Carthage/Checkouts/CwlPreconditionTesting/Dependencies/CwlCatchException/Sources/CwlCatchExceptionSupport/include/CwlCatchException.h) to be committed on Git.

I reckon this might be a [`Accio`](https://github.com/JamitLabs/Accio) or [`gitignore`](https://github.com/github/gitignore) bug but I felt it was still worth flagging here, (a) in case renaming the directory would be an option and (b) to help my fellow developers identify the source of the error when they meet it.

### Environment

List the software versions you're using:

 - Quick: *2.2.0*
 - Nimble: *8.0.5*
 - Xcode Version: *11.3.1 (11C504)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: `Xcode Default`

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *1.8.4* (Use `pod --version` in Terminal)

**Comment by dirtyhenry** [comment] 2020-01-30 14:36
Oops. https://github.com/Quick/Nimble/issues/696 🤦‍♂

**Comment by ikesyo** [comment] 2020-01-31 04:00
Duplicate of https://github.com/Quick/Nimble/issues/490#issuecomment-548433903

**Closed by ikesyo** 2020-01-31 04:00 UTC
