### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_catchExceptionOfKind"

### ISSUE THREAD

**Issue by robinhayward** [Quick/Nimble#705] opened 2019-10-19 09:53 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Moved my code from a framework to a Swift Package.
Added Nimble as a dependency to the Swift Package I now have to share some code between my iOS apps.

### What did you expect to happen?

I expected Nimble to be available in the tests files and all my existing tests to run.

### What actually happened instead?

It looks like Xcode installs the Nimble package but the project fails to build if I try to run tests.

The build error:

Undefined symbols for architecture x86_64:
  "_catchExceptionOfKind", referenced from:
      CwlCatchException.(catchReturnTypeConverter in _841BEC3F94220F0DFD4EA4E9DDB3DC93)<A where A: __C.NSException>(_: A.Type, block: () -> ()) -> A? in CwlCatchException.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Environment

List the software versions you're using:

 - Nimble: .package(url: "https://github.com/Quick/Nimble", from: "8.0.1"),
 - Xcode Version: 11.1 (11A1027)
 - Swift Version: Swift 5

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Swift Package Manager: Apple Swift Package Manager - Swift 5.1.0 (swiftpm-14696)

### Package file used:

// swift-tools-version:5.1
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "BumpPackage",
    platforms: [
        .iOS(.v11), .macOS(.v10_13),
    ],
    products: [
        .library(
            name: "BumpPackage",
            targets: ["BumpPackage"]),
    ],
    dependencies: [
      .package(url: "https://github.com/Quick/Nimble", from: "8.0.1"),
    ],
    targets: [
        .target(
            name: "BumpPackage",
            dependencies: ["Nimble"]),
        .testTarget(
            name: "BumpPackageTests",
            dependencies: ["BumpPackage", "Nimble"]),
    ]
)

**Comment by ikesyo** [comment] 2019-10-19 13:37
Duplicate of #696.

**Closed by ikesyo** 2019-10-19 13:37 UTC
