### ISSUE TITLE
Occasionaly test failure with message `expected to eventually be falsy, got <0>`

### ISSUE THREAD

**Issue by manuyavuz-pointr** [Quick/Nimble#845] opened 2020-11-25 18:03 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I have a UI test case with following expectation:

```objc
expect(self.app.keyboards.firstMatch.exists).withTimeout(5).toEventually(beFalsy());
```

This code occasionally fails on CI builds (when run with address sanitizer enabled) with the following failure message:
```
expected to eventually be falsy, got <0>
```

### What did you expect to happen?

This error should never happen in my opinion as the expression in `expect()` returns a `BOOL`, and matcher is `beFalsy()`, which should both match with `false` boolean values and `nil` values as it's implicitly falsy.

### What actually happened instead?

This code occasionally fails on CI builds (when run with address sanitizer enabled) with the following failure message:
```
expected to eventually be falsy, got <0>
```

### Environment

List the software versions you're using:

- Nimble: *9.0.0*
- Xcode Version: *12.0* (Open Xcode; In menubar: Xcode > About Xcode)
- Swift Version: *Xcode Default* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Cocoapods: *1.10.0* (Use `pod --version` in Terminal)

### Project that demonstrates the issue

I don't have a project as I could not reproduce the issue locally yet.

Any guess how this could happen?

Thanks!

**Comment by ikesyo** [comment] 2021-02-05 17:15
Duplicate of #360.

**Closed by ikesyo** 2021-02-05 17:15 UTC
