### ISSUE TITLE
Tests fail to compile with issue "Illegal instruction: 4"

### ISSUE THREAD

**Issue by dcarmo-tribalscale** [Quick/Nimble#839] opened 2020-10-23 14:56 UTC
- [X] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

```swift
describe("Employee Model") {
    let employeeDataProvider = EmployeeDataProvider()
    let decoder = JSONDecoder()
    decoder.keyDecodingStrategy = .convertFromSnakeCase
    
    context("Check for required fields") {
        it("throws if uuid is missing") {
            let respData = employeeDataProvider.jsonDataSingleEmployee(removingKey: .uuid)
            expect { try decoder.decode(Employee.self, from: respData) }.to(throwError()) // PROBLEM LINE
        }
    }
}
```

Using the following `expect` statement causes the swift compiler to crash with the classic _An internal error occurred. Source editor functionality is limited. Attempting to restore..._ and the tests fail to compile with a `Illegal instruction: 4`

```swift
expect { try decoder.decode(Employee.self, from: respData) }.to(throwError())
```

The issue seems to be caused by there not being brackets around the closure in `Nimble` (the documentation here https://github.com/Quick/Nimble#swift-error-handling shows that it shouldn't require the brackets around it and those missing brackets are what use the explicit declaration below).

To solve the issue and make the compiler happy I updated my implementation to explicitly use this definition of expect.

```swift
/// Make an expectation on a given actual value. The closure is lazily invoked.
public func expect<T>(_ file: FileString = #file, line: UInt = #line, expression: @escaping () throws -> T?) -> Expectation<T> {
    // ... CODE ...
}
```

This can be done by specifying the `expression` param in the method. 

```swift
expect(expression: { try decoder.decode(Employee.self, from: respData) }).to(throwError())
```

This will cause the compiler to be happy and the test to work properly, however the documentation shows that it shouldn't be required.

### What did you expect to happen?

The test should compile properly

### What actually happened instead?

Failure to compile with issue  _An internal error occurred. Source editor functionality is limited. Attempting to restore..._ and the tests fail to compile with a `Illegal instruction: 4`

### Environment

List the software versions you're using:

- Quick: *2.2.0*
- Nimble: *8.0.5*
- Xcode Version: *12.0.1 (12A7300)*
- Swift Version: 
Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
Target: x86_64-apple-darwin19.6.0

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Cocoapods: *1.10.0*

**Comment by ikesyo** [comment] 2020-10-23 16:14
Duplicate of #809. Please update to Nimble v9.

**Closed by ikesyo** 2020-10-23 16:14 UTC

**Comment by dcarmo-tribalscale** [comment] 2020-10-23 17:04
Sorry I missed that issue. Thanks for the info I'll update now!
