### ISSUE TITLE
Link Nimble fails due to library not found for -lswiftXCTest

### ISSUE THREAD

**Issue by Mountainbrussells** [Quick/Nimble#945] opened 2021-10-06 17:28 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/main/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

Build my project for testing for testing.,
I have deleted all pods DDD and re-installed pods and it is still happening

### What did you expect to happen?

Project to build and tests to run

### What actually happened instead?

Build failed at 
Link Nimble
Ld /Users/benrussell/Library/Developer/Xcode/DerivedData/Metal-dqlqgscjiqhfonafejcisrunytzo/Build/Products/Debug-iphonesimulator/Nimble/Nimble.framework/Nimble normal (in target 'Nimble' from project 'Pods')
    cd /Users/benrussell/Desktop/DIios/metal-ios/Metal/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios8.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk -L/Users/benrussell/Library/Developer/Xcode/DerivedData/Metal-dqlqgscjiqhfonafejcisrunytzo/Build/Products/Debug-iphonesimulator/Nimble -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/usr/lib/swift -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib -F/Users/benrussell/Library/Developer/Xcode/DerivedData/Metal-dqlqgscjiqhfonafejcisrunytzo/Build/Products/Debug-iphonesimulator/Nimble -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/Developer/Library/Frameworks -filelist /Users/benrussell/Library/Developer/Xcode/DerivedData/Metal-dqlqgscjiqhfonafejcisrunytzo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Nimble.build/Objects-normal/x86_64/Nimble.LinkFileList -install_name @rpath/Nimble.framework/Nimble -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/benrussell/Library/Developer/Xcode/DerivedData/Metal-dqlqgscjiqhfonafejcisrunytzo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Nimble.build/Objects-normal/x86_64/Nimble_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -Xlinker -debug_variant -fobjc-arc -fobjc-link-runtime -fapplication-extension -fprofile-instr-generate -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/benrussell/Library/Developer/Xcode/DerivedData/Metal-dqlqgscjiqhfonafejcisrunytzo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Nimble.build/Objects-normal/x86_64/Nimble.swiftmodule -Xlinker -no_application_extension -weak-lswiftXCTest -weak_framework XCTest -framework Foundation -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/benrussell/Library/Developer/Xcode/DerivedData/Metal-dqlqgscjiqhfonafejcisrunytzo/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Nimble.build/Objects-normal/x86_64/Nimble_dependency_info.dat -o /Users/benrussell/Library/Developer/Xcode/DerivedData/Metal-dqlqgscjiqhfonafejcisrunytzo/Build/Products/Debug-iphonesimulator/Nimble/Nimble.framework/Nimble

ld: library not found for -lswiftXCTest
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Environment

List the software versions you're using:

- Quick: *2.2.1*
- Nimble: *8.1.2*
- Xcode Version: *13.0* 
- Swift Version: *Xcode Default* 

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Cocoapods: *1.11.2*

**Comment by ikesyo** [comment] 2021-10-07 01:17
Duplicate of #855. Please update to v9.0.1 or later.

**Closed by ikesyo** 2021-10-07 01:17 UTC
