### ISSUE TITLE
Nimble raise Exception instead of using XCTAssertFail in Swift ( installed from SPM )

### ISSUE THREAD

**Issue by cinoss** [Quick/Nimble#383] opened 2017-01-02 04:00 UTC
### What did you do?

Use Nimble for unit testing in vapor ( or a swift package in general )

### What did you expect to happen?

A concise message when an assertion fails

### What actually happened instead?

A long stack dump when that happens. When I debug the code ( installed from swift package manager) `#if _runtime(_ObjC)` branch is used, instead of the other with `XCTAssertFail`.

### Environment

List the software versions you're using:

 - Nimble: *5*
 - Xcode Version: *8.2.1 (8C1002)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *3.0.2* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:
inal)
 - Swift Package Manager *3.0.2 (swiftpm-11750)*

**Comment by ikesyo** [comment] 2017-01-02 04:39
Is this a duplicate of #367? If so that is fixed in `master` by #372 (but not released yet).

**Comment by jeffh** [comment] 2017-01-06 23:24
I'll get around to cutting a new release soon (after I finish vacation-ing 😅 ). Look for it sometime next week.

**Comment by jeffh** [comment] 2017-01-28 21:18
Closing, Nimble 6.0.0 / 6.0.1 is out which includes this fix.

**Closed by jeffh** 2017-01-28 21:18 UTC
