### ISSUE TITLE
Forward declaration errors with ObjC tests

### ISSUE THREAD

**Issue by Noobish1** [Quick/Nimble#129] opened 2015-05-21 06:45 UTC
I'm using Nimble 1.0.0-rc.1 via Cocoapods for some unit tests. I'm running Xcode 6.3.1 on 10.10.3.

```objc
#import <Quick/Quick.h>
#import <Nimble/Nimble.h>

QuickSpecBegin(TestSpec)

describe(@"an object", ^{
    context(@"when created", ^{
        __block NSObject *object = nil;
        
        beforeEach(^{
            object = [[NSObject alloc] init];
        });
        
        it(@"should not be nil", ^{
            expect(object).notTo(beNil());
        });
    });
});

QuickSpecEnd
```
The above causes: 
> Property 'notTo' cannot be found in forward class object 'NMBExpectation'

If I add `#import <Nimble/Nimble-Swift.h>` it compiles.

**Comment by jeffh** [comment] 2015-05-23 22:26
Hey @Noobish1,

What cocoapods version are you using?

I'm suspicious that it's related to https://github.com/Quick/Nimble/issues/128. I'll try to get some time to look into this in the next few days since I did see this before.

**Comment by Noobish1** [comment] 2015-05-23 22:57
We're using 0.37.1

**Comment by jeffh** [comment] 2015-05-26 01:04
Thanks @Noobish1. I was able to reproduce. It seems like OS X frameworks want this import, but iOS refuses to build if this import line is present. Needs some more investigation.

**Comment by objczl** [comment] 2015-05-29 13:29
+1

**Comment by jeffh** [comment] 2015-05-31 06:33
I've looked into this a bit further. It's either something with cocoapods or xcode. The `#import <Nimble/Nimble-Swift.h>` line seems required for subsequent build of Nimble that isn't the first build. Putting this first line will always make the first build fail because the "Nimble" module doesn't exist.

**Comment by jeffh** [comment] 2015-06-25 08:04
Closing this issue. I've filed a radar to the fruit company. The easiest workaround is to use `@import Nimble;`. I've updated the README to use that instead.

Thanks for reporting the issue :smile:.

**Closed by jeffh** 2015-06-25 08:04 UTC
Labels: bug, help wanted

**Comment by poetmountain** [comment] 2016-01-15 04:44
I know this issue is closed, but I'm seeing this same issue and neither of the workarounds noted in this thread (use ```@import``` or importing ```<Nimble/Nimble-Swift.h>```) are working. Xcode can't find either of those from my Objective-C test cases.  I'm using Cocoapods 0.39.0 and Xcode 7.2, and Nimble 3.0.0.

**Comment by oks** [comment] 2016-03-06 14:56
+1, any updates, team?

**Comment by oks** [comment] 2016-03-07 12:41
How it works for me:
xcode 7.2, ios 9, objective-c
1) install as submodule
2) include framework following installation instructions (install via cocopods didn't work properly)
3) as mentioned above add file <Nimble/Nimble-Swift.h> to your file. 
3.1) I've created pch file and put all imports there.
