### ISSUE TITLE
23 compiler warnings in Xcode 8 + Swift 3

### ISSUE THREAD

**Issue by ohadnav** [Quick/Nimble#452] opened 2017-07-30 11:26 UTC
1. 'Matcher' is deprecated: Use to Predicate instead
2. 'NonNilMatcherFunc' is deprecated: Use to Predicate instead
3. ContainElementSatisfying.swift:41:21: Variable 'iterator' was never mutated; consider changing to 'let' constant

**Comment by ikesyo** [comment] 2017-07-30 11:53
This is a duplicate of #444.

**Closed by ikesyo** 2017-07-30 11:53 UTC
