### ISSUE TITLE
Couple of unexpected behaviors for contain matcher in 2.0.0-rc.3

### ISSUE THREAD

**Issue by nikita-leonov** [Quick/Nimble#195] opened 2015-09-26 02:13 UTC
Below are two behaviors for contain that I can not explain so far:
![mistery 1](https://www.evernote.com/shard/s70/sh/cac119c4-e8fd-4d96-9b67-966ee00a7a35/1d525ebf224df959/res/d6693c9e-4884-46f5-8e5d-a078c044fc42/skitch.png)
![mistery 2](https://www.evernote.com/shard/s70/sh/c173926d-7ba5-4bb0-8eed-bb5a8f99bdc1/57bc29dc9c1b64be/res/83b491f7-795c-40e4-866e-2548ab99f924/skitch.png)
Second scenario achieved by replacing type in the same code. Any ideas what is going on?

**Comment by jeffh** [comment] 2015-10-04 03:16
Hey @nikita-leonov,

I'm not sure about why. It seems like an bug report for Apple. It seems like the the type inferencer of the Swift compiler decides to use the NMBContainer specific version of `contains`, which it then fails later down the line:

<img width="1018" alt="screen shot 2015-10-03 at 8 15 41 pm" src="https://cloud.githubusercontent.com/assets/68616/10266264/a91d9254-6a0b-11e5-8e54-3fb27eb8c821.png">

- Jeff

**Comment by jeffh** [comment] 2016-10-04 05:23
I can't reproduce this anymore, so I'm closing the issue. It seems like the Swift Compiler has fixed it. Feel free to reopen this issue if you still encounter this bug.

**Closed by jeffh** 2016-10-04 05:23 UTC
Labels: bug, tricky
