### ISSUE TITLE
waitUntil(timeout: 10) { done in is not working in my code

### ISSUE THREAD

**Issue by bhawna08** [Quick/Nimble#180] opened 2015-09-02 13:01 UTC
```swift
waitUntil(timeout: 10) { done in
  // do some stuff that takes a while...
  NSThread.sleepForTimeInterval(1)
  done()
}
```
method is not working in my code, please help.

**Comment by jeffh** [comment] 2015-09-03 16:00
hey @bhawna08, what do you mean by doesn't work? What error message do you get?

**Comment by ashfurrow** [comment] 2015-09-03 17:24
I'm seeing problems too, with test cases similar to [this](https://github.com/Quick/Nimble/issues/48#issuecomment-61446381). The failures are intermittent, but I've reproduced them with the following test:

```swift
waitUntil { (done) -> Void in
    done()
}
```

Based on the other thread, it seems like calling `done()` before the closure returns is _not_ supported behaviour. @jeffh could you confirm?

**Comment by jeffh** [comment] 2015-09-06 23:52
I'm unfortunately, unable to reproduce this on my local machine (high-end MBP 15' mid-2014). Running Nimble's test suite multiple times (which [includes that code](https://github.com/Quick/Nimble/blob/swift-2.0/NimbleTests/AsynchronousTest.swift#L38-L40)) doesn't seem to reproduce for me.

**Comment by jeffh** [comment] 2016-01-18 21:14
I have merged a fix into master. Please let me know if you have any issues (a release will come out later today).

**Comment by ashfurrow** [comment] 2016-01-19 00:13
Fab, thanks!

**Comment by jeffh** [comment] 2016-01-19 09:34
Closing. This is now in v3.1.0.

**Closed by jeffh** 2016-01-19 09:34 UTC
Labels: bug
