### ISSUE TITLE
Xcode 12 beta 5 - Project w/ Nimble dependency fails to build

### ISSUE THREAD

**Issue by deanharel** [Quick/Nimble#812] opened 2020-08-25 14:04 UTC
- [V ] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

- Installed the latest Xcode, version **12.0 beta 5 (12A8189h)**
- Created a completely new Xcode Project, using the App template.
- Configured `Carthage` and added a `Cartfile`, with the following dependencies:

```
github "Quick/Nimble"
```
- Run the following command:

```
xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT
'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A8189h = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage bootstrap --platform iOS --cache-builds
```
**NOTE:** Setting "EXCLUDED_ARCHS" to arm architectures, as a workaround for Xcode 12 using Carthage. [More info](https://github.com/Carthage/Carthage/issues/3019)

### What did you expect to happen?

- A Nimble framework under Carthage/Build folder should've been created.

### What actually happened instead?

Carthage/Build was not created. Received a build failure instead, with this partial log output:
```
import XCTest
       ^

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
	CompileSwift normal i386
(3 failures)
```

### Environment

- Nimble: 8.1.1
- Xcode Version: *12.0 beta 5 (12A8189h)*
- Swift Version: *Xcode Default (5.3 beta)*
- Carthage: *0.35.0* 

### Project that demonstrates the issue
[Link to the project](https://gofile.io/d/oyDJeK)

**Comment by ikesyo** [comment] 2020-09-01 01:34
This would be a duplicate of #809.

**Closed by ikesyo** 2020-09-01 01:34 UTC
