### ISSUE TITLE
CocoaPods 0.36 Beta swift 1.2 does not compile because of "as!" custing

### ISSUE THREAD

**Issue by sergdort** [Quick/Nimble#101] opened 2015-02-24 11:50 UTC

**Comment by gyemme** [comment] 2015-02-24 14:33
@sergdort this issue could potentially be a duplicate of this https://github.com/Quick/Nimble/issues/98. Which version of Xcode are you using ?

**Comment by sergdort** [comment] 2015-02-24 14:38
I'm using Xcode 6.1.1

**Comment by sergdort** [comment] 2015-02-24 14:40
I've actually replaced all "as!" with "as" and it compiles for now.

**Comment by gyemme** [comment] 2015-02-24 15:09
That's one way to do it but as @jeffh mentioned in the previous post use swift-1.1 branch for Xcode 6.1.1

**Comment by jeffh** [comment] 2015-02-24 22:49
Yeah, Nimble v0.3.0 is the latest swift 1.1 release while v0.4.0 is the latest swift 1.2 release. master refers to Swift 1.2 while the `swift-1.1` branch refers to swift-1.1 work.

**Closed by jeffh** 2015-02-24 22:49 UTC
