### ISSUE TITLE
expect(_:file:line)/expect(_:line:expression) overload ambiguity in Xcode 12 beta 5

### ISSUE THREAD

**Issue by nikolaykasyanov** [Quick/Nimble#811] opened 2020-08-20 12:24 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

I tried to compile my project with Xcode 12 beta 5 and got the error at calls like this:

```swift
expect {
    try sut.doSomething()
}.to(throwError(expectedError))
```

I guess this might be related to the new trailing closure syntax in Swift 5.3.

### What did you expect to happen?

I expect this code to compile.

### What actually happened instead?

The code doesn't compile due to following error: "Ambigous use of expect". The mentioned `expect` overloads are listed by Xcode as candidates.

### Environment

List the software versions you're using:

- Quick: *3.0.0*
- Nimble: *8.1.1*, *9.0.0-rc.1*
- Xcode Version: *12.0 beta 5 (12A8189h)* (Open Xcode; In menubar: Xcode > About Xcode)
- Swift Version: *?.?* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

- Cocoapods: *1.10.0.beta.1*

### Project that demonstrates the issue

https://github.com/nikolaykasyanov/NimbleCompilationFailure

**Comment by ikesyo** [comment] 2020-08-20 13:34
Duplicate of #809.

**Closed by ikesyo** 2020-08-20 13:34 UTC

**Comment by nikolaykasyanov** [comment] 2020-08-20 13:55
@ikesyo my bad, thanks for referencing.
