### ISSUE TITLE
sometimes sleep for a long time with waitUntilTimeout

### ISSUE THREAD

**Issue by soranoba** [Quick/Nimble#418] opened 2017-04-15 05:18 UTC
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### Description

I write a lot of asynchronous tests, but I am sure that it sometimes will block for a long time with waitUntilTimeout (with Objective-C).

Reproduction is very easy.

1. First, please make sure the following code sleeps for a long time in the middle.
https://github.com/soranoba/Nimble/commit/37e17346eeaaa00085ec7c346edea2c6257f5897

```objc
    for (int i = 0; i < 10000; i++) {
        waitUntilTimeout(1, ^(void (^done)(void)) {
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                NSLog(@"done : %d", i);
                done();
            });
        });
    }
```

2. Please patch this and run it. It will not sleep!
https://github.com/soranoba/Nimble/commit/f95fb62fd6703061d2dd2bddb953b3d3f549faf8

All of these commits are on the same branch.
https://github.com/soranoba/Nimble/commits/bug/block_at_waitUntilTimeout

I think that RunLoop.current.run blocked for a long time because the schedule interrupt does not run for some reason (I do not known this).
My patch avoids this by explicitly setting a deadline.

I do not know if this fix is correct, so I made an issue before PR.

### Environment

List the software versions you're using:

 - Nimble: v6.1.0
 - Xcode Version: 8.2.1

**Comment by ikesyo** [comment] 2020-03-30 19:19
Marking this as a duplicate of #509 and fixed by #721.

**Closed by ikesyo** 2020-03-30 19:19 UTC
