### ISSUE TITLE
use of unresolved identifier 'NMBExceptionCapture'

### ISSUE THREAD

**Issue by gyemme** [Quick/Nimble#77] opened 2015-01-08 23:39 UTC
Created the branch new project. Added the following podfile.

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target "<My Test target name>" do
  pod 'Quick', :git => 'https://github.com/Quick/Quick', :tag => 'v0.2.2'
  pod 'Nimble', :git => "https://github.com/Quick/Nimble"
end

When i compile the app I get the following error. 

Pods/Nimble/Nimble/Adapters/AssertionRecorder.swift:44:20: error: use of unresolved identifier 'NMBExceptionCapture'
    let capturer = NMBExceptionCapture(handler: nil, finally: ({

Use of unresolved Identifier 'NMBExceptionCapture'. In DSL.m i get the error use of 'Nimble/Nimble-swift.h' file not found for #import <Nimble/Nimble-Swift.h>.

**Comment by jeffh** [comment] 2015-01-12 18:37
Hey @gowthamyemme, sorry for the slow reply (Happy holidays!).

Are you using swift or objective-c? I'll try and get around to manually verifying this later today.

**Comment by gowthamyemme** [comment] 2015-01-14 13:57
@jeffh I am using a swift project.

**Comment by jeffh** [comment] 2015-01-18 01:45
Hey @gowthamyemme, I couldn't reproduce your issue. Is your derived data clean? What version of Xcode are you using?

**Comment by eliperkins** [comment] 2015-01-23 22:15
Running up against the same issue myself, blew away derived data several times before declaring myself insane :stuck_out_tongue: . 

I'm on Xcode Version 6.2 (6C107a), also got the same issue against Xcode Version 6.1.1 (6A2008a). Glad to help give more details!

**Comment by modocache** [comment] 2015-01-23 22:25
> blew away derived data several times before declaring myself insane

Sorry if I'm misunderstanding--this means that the build error occurs every time, even after clearing derived data, right? Just want to make sure! :monkey:

**Comment by eliperkins** [comment] 2015-01-23 22:25
Haha yup yup. Still occurs even after cleaning derived data.

**Comment by jeffh** [comment] 2015-01-25 08:53
Do you have a sample project that exhibits this issue? Or some detailed steps to reproduce?

**Comment by eliperkins** [comment] 2015-01-26 16:11
Unfortunately, the project I had this crop up with is not a project I can share. I can share with you how I got here though.

The project has used Cocoapods for a while, 0.35.0 at the time. I cloned both Quick and Nimble locally, tweaked the deployment target on both projects and podspecs to be iOS 7 (the goal of the exercise being to validate Quick/Quick#206). I added Quick and Nimble to my podfile under my test target (which included a couple other pods, FWIW, OHHTTPStubs and OCMock). Now using Cocoapods 0.36.0, I `pod install`ed. I went back into the project and added `#import <Quick/Quick.h>` to my pch. I tried building the tests, but the build failed when trying to build Nimble, saying `Use of unresolved Identifier 'NMBExceptionCapture'.` Same issue occurred after a clean and build and after a `rm -rf` of derived data, a clean, and a build.

I just tried replicating the same steps on another (OSS) project, but it didn't occur again there, everything built in that project just fine. Might be best to chalk this up to a build tools (Swift and/or Cocoapods) failure, but figured it was worthwhile to chime in here and see if I could give some more info.

**Comment by gowthamyemme** [comment] 2015-02-07 00:20
Sorry for the delayed response. I created a sample project with that issue here https://github.com/gowthamyemme/NimbleIssue. The steps to recreate the issue are simple.

Create a brand new swift project
Add the following pod file 

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'iOSUnitTestingTests', :exclusive => true do
  pod 'Quick'
  pod 'Nimble'
end

Run the tests. 
![screen shot 2015-02-06 at 4 20 31 pm](https://cloud.githubusercontent.com/assets/4649915/6089716/0b87bc96-ae1c-11e4-9e0d-602d99c8a0b3.png)

**Comment by gowthamyemme** [comment] 2015-02-09 22:31
I have a work around for this problem which might provide some more information for debugging. 

use the following in your podfile 

  	pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :commit => 'f8c9ff9f499fc5ea72ff55c1c5eed32e1ff303ea'
	pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :commit => '9538a301d5320fd607f01c931dc282868b0e827a'

use version 0.36.0.beta.2 for pods

**Comment by jeffh** [comment] 2015-02-10 21:01
Hey @gyemme, thanks for the sample project! It's been super helpful.

It seems like the podfile was generated from `0.35.0` (See [podfile.lock](https://github.com/gyemme/NimbleIssue/blob/master/Podfile.lock#L13)).

Beta cocoa pods should be generating frameworks IIRC. If I rerun `pod install` with no podfile changes but using `0.36.0.beta.2`, it works. I'm tempted to close this issue as an older version of cocoa pods use. Hopefully when cocoa pods official releases swift support this gotcha won't happen.

**Comment by jeffh** [comment] 2015-02-16 08:01
Closing. Reopen if this surfaces again on later cocoapods versions.

**Closed by jeffh** 2015-02-16 08:01 UTC
Labels: bug
